services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    volumes:
      - static_volume:/app/desafio_iabs/staticfiles
      - db_volume:/app/desafio_iabs
    restart: unless-stopped

volumes:
  static_volume:
  db_volume: